# Exercises (22/09)

**Exercise 1**: Create two 3x3 NumPy arrays `A` and `B` with random integer values between `0` and `10`. Perform the following operations:

1. Element-wise addition of `A` and `B`.
2. Element-wise multiplication of `A` and `B`.
3. Matrix multiplication (dot product) of `A` and `B` (look this up).
4. Find the transpose of `A`.

In [3]:
import numpy as np
import pandas as pd

A = np.random.randint(0, 11, (3, 3))
B = np.random.randint(0, 11, (3, 3))

add_result = A + B
mul_result = A * B
dot_result = A @ B
transpose_A = A.T

print("A:\n", A)
print("B:\n", B)
print("Element addition:\n", add_result)
print("Element multiplication:\n", mul_result)
print("Matrix multiplication:\n", dot_result)
print("Transpose\n", transpose_A)

A:
 [[ 3  9  5]
 [ 4  1 10]
 [ 3  7  7]]
B:
 [[6 1 7]
 [0 8 5]
 [3 7 6]]
Element addition:
 [[ 9 10 12]
 [ 4  9 15]
 [ 6 14 13]]
Element multiplication:
 [[18  9 35]
 [ 0  8 50]
 [ 9 49 42]]
Matrix multiplication:
 [[ 33 110  96]
 [ 54  82  93]
 [ 39 108  98]]
Transpose
 [[ 3  4  3]
 [ 9  1  7]
 [ 5 10  7]]


**Exercise 2**: Create a 5x5 array of random integers between 0 and 20, and perform the following tasks:

1. Extract the second row.
2. Extract the third column.
3. Extract a `2x2` sub-array from the bottom-right corner.
4. Set all the elements in the first row to `100`.

In [4]:
arr = np.random.randint(0, 21, (5, 5))

second_row = arr[1, :]
third_column = arr[:, 2]
bottom_right_sub = arr[3:, 3:]
arr[0, :] = 100

print("array:\n", arr)
print("second row:\n", second_row)
print("third column:\n", third_column)
print("sub-array:\n", bottom_right_sub)


array:
 [[100 100 100 100 100]
 [ 13  10  18  12   4]
 [  2   6   1  19   0]
 [  2  17  10   3   9]
 [ 17  17   8  20  10]]
second row:
 [13 10 18 12  4]
third column:
 [100  18   1  10   8]
sub-array:
 [[ 3  9]
 [20 10]]


**Exercise 3**: Create a NumPy array of `50` random floating-point numbers between `0` and `1`. Calculate the following statistics:

1. Mean of the array.
2. Median of the array.
3. Standard deviation.
4. Minimum and maximum values.

In [5]:
arr = np.random.rand(50)

mean_val = arr.mean()
median_val = np.median(arr)
std_val = arr.std()
min_val = arr.min()
max_val = arr.max()

print("mean:", mean_val)
print("median:", median_val)
print("std:", std_val)
print("min:", min_val)
print("max:", max_val)

mean: 0.4778612020797891
median: 0.41949918417603466
std: 0.2923773907859694
min: 0.003033376871365734
max: 0.9639596462212594


**Exercise 4**: Create a NumPy array with values from `1` to `16` (reasearch `arange` function). Reshape the array into the following shapes:

1. A `4x4` matrix.
2. A `2x8` matrix.
3. A `16x1` matrix.

In [6]:
arr = np.arange(1, 17)

arr_4x4 = arr.reshape(4, 4)
arr_2x8 = arr.reshape(2, 8)
arr_16x1 = arr.reshape(16, 1)

print("4x4 matrix:\n", arr_4x4)
print("2x8 matrix:\n", arr_2x8)
print("16x1 matrix:\n", arr_16x1)

4x4 matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
2x8 matrix:
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
16x1 matrix:
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]]


**Exercise 5**: Create a `6x6` NumPy array with random integers between `0` and `50`. Use Boolean indexing to:

1. Find all elements greater than `25`.
2. Replace all elements less than `10` with `-1`.
3. Count how many elements are even.

In [7]:
arr = np.random.randint(0, 51, (6, 6))

greater_25 = arr[arr > 25]
arr[arr < 10] = -1
even_count = np.sum(arr % 2 == 0)

print("array:\n", arr)
print("elements greater than 25:\n", greater_25)
print("number of even elements:", even_count)

array:
 [[18 24 13 45 35 19]
 [49 27 48 35 45 -1]
 [26 19 44 40 39 28]
 [27 28 48 46 50 26]
 [33 -1 41 46 12 23]
 [32 30 14 34 21 44]]
elements greater than 25:
 [45 35 49 27 48 35 45 26 44 40 39 28 27 28 48 46 50 26 33 41 46 32 30 34
 44]
number of even elements: 19


**Exercise 1: Exploring Categorical Data**

Create a pandas DataFrame representing a group of employees. Include two categorical columns: "Department" (with categories Sales, Marketing, and HR) and "Job Level" (with categories Junior, Intermediate, and Senior).

**Tasks**:
1. Calculate and display the count of employees in each department and at each job level using the `value_counts()` method.
2. Perform `one-hot encoding` for the "Department" column to create binary columns for each department.
3. Rename the categories in the `"Job Level"` column to abbreviations, such as "Jr" for Junior, "Int" for Intermediate, and "Sr" for Senior.

In [8]:
df = pd.DataFrame({
    "Department": np.random.choice(["Sales", "Marketing", "HR"], 15),
    "Job Level": np.random.choice(["Junior", "Intermediate", "Senior"], 15)
})

dept_counts = df["Department"].value_counts()
job_counts = df["Job Level"].value_counts()

dept_onehot = pd.get_dummies(df["Department"])
df["Job Level"] = df["Job Level"].replace({"Junior": "Jr", "Intermediate": "Int", "Senior": "Sr"})

print("department counts:\n", dept_counts)
print("job level counts:\n", job_counts)
print("one-hot encoding of department:\n", dept_onehot)
print("abbreviated job levels:\n", df)

department counts:
 Department
Sales        7
Marketing    5
HR           3
Name: count, dtype: int64
job level counts:
 Job Level
Senior          6
Junior          5
Intermediate    4
Name: count, dtype: int64
one-hot encoding of department:
        HR  Marketing  Sales
0   False      False   True
1    True      False  False
2   False       True  False
3    True      False  False
4   False       True  False
5   False       True  False
6   False      False   True
7   False      False   True
8   False      False   True
9   False      False   True
10  False      False   True
11  False       True  False
12   True      False  False
13  False       True  False
14  False      False   True
abbreviated job levels:
    Department Job Level
0       Sales        Jr
1          HR        Jr
2   Marketing        Sr
3          HR       Int
4   Marketing       Int
5   Marketing        Sr
6       Sales        Jr
7       Sales        Jr
8       Sales        Jr
9       Sales        Sr
10      Sales      

**Exercise 2: Analyzing Categorical Data**

Load a dataset with categorical columns, such as the Titanic dataset.

**Tasks**:
1. Calculate the survival rate for passengers by class (1st, 2nd, 3rd).
2. Determine the most common embarkation port for passengers.
3. Create a pivot table to compare the average fare paid by passengers in different classes and different embarkation ports.

In [9]:
import seaborn as sns

titanic = sns.load_dataset("titanic")

survival_by_class = titanic.groupby("pclass")["survived"].mean()
most_common_port = titanic["embarked"].mode()[0]
fare_pivot = titanic.pivot_table(values="fare", index="pclass", columns="embarked", aggfunc="mean")

print("survival rate by class:\n", survival_by_class)
print("most common embarkation port:", most_common_port)
print("pivot table:\n", fare_pivot)

survival rate by class:
 pclass
1    0.629630
2    0.472826
3    0.242363
Name: survived, dtype: float64
most common embarkation port: S
pivot table:
 embarked           C          Q          S
pclass                                    
1         104.718529  90.000000  70.364862
2          25.358335  12.350000  20.327439
3          11.214083  11.183393  14.644083


**Exercise 3: Working with Ordinal Categorical Data**

**Tasks**:
1. Create a DataFrame with an ordinal categorical column like `"Rating"` (e.g., Poor, Fair, Good, Excellent).
2. Define the custom order for the ordinal categories.
3. Sort the DataFrame based on the `"Rating"` column, considering the custom order.

In [10]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Rating": np.random.choice(["Poor", "Fair", "Good", "Excellent"], 5)
})

rating_order = ["Poor", "Fair", "Good", "Excellent"]
df["Rating"] = pd.Categorical(df["Rating"], categories=rating_order, ordered=True)
df_sorted = df.sort_values("Rating")

print("original dataframe:\n", df)
print("sorted dataframe:\n", df_sorted)

original dataframe:
       Name     Rating
0    Alice       Poor
1      Bob       Fair
2  Charlie  Excellent
3    David       Fair
4      Eva       Fair
sorted dataframe:
       Name     Rating
0    Alice       Poor
1      Bob       Fair
3    David       Fair
4      Eva       Fair
2  Charlie  Excellent


# Exercises (24/09)

**Exercise 1**: Create a 1D array of numbers from `0` to `9`:

In [11]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


**Exercise 2**: Create a `3×3` numpy array of all True:

In [12]:
arr = np.ones((3, 3), dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


**Exercise 3**: Extract all `odd` numbers from `a`:

In [14]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = arr[arr % 2 == 1]
print(odd_numbers)

[1 3 5 7 9]


**Exercise 4**: Replace all `odd` numbers in arr with `-1`:

In [15]:
arr[arr % 2 == 1] = -1
print(arr)  

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**Exercise 5**: Convert a 1D array to a 2D array with `2` rows:

In [16]:
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]
