# Homework 4 - NumPy Arrays

This is an **individual** assignment. Total: 20 points. Due:**<span style="color:red">  Sunday, September 28th, 11:59 pm </span>**.

In [1]:
import numpy as np
import pandas as pd

### Task 1: Generate a one-dimensional array consisting of `30` equally spaced values ranging from `5` to `50`, inclusive.

In [2]:
arr = np.linspace(5, 50, 30)
print(arr)

[ 5.          6.55172414  8.10344828  9.65517241 11.20689655 12.75862069
 14.31034483 15.86206897 17.4137931  18.96551724 20.51724138 22.06896552
 23.62068966 25.17241379 26.72413793 28.27586207 29.82758621 31.37931034
 32.93103448 34.48275862 36.03448276 37.5862069  39.13793103 40.68965517
 42.24137931 43.79310345 45.34482759 46.89655172 48.44827586 50.        ]


### Task 2: Create an array of shape `(4, 5)` and populate it with random samples from a `uniform distribution` over `[0, 1)`.

In [3]:
arr_uniform = np.random.uniform(0, 1, (4, 5))
print(arr_uniform)

[[0.3837487  0.94271026 0.94417743 0.30979901 0.31867942]
 [0.4573296  0.1975044  0.74689528 0.12877244 0.94867386]
 [0.61621354 0.182366   0.24184948 0.67618773 0.33284642]
 [0.98130545 0.68026776 0.72604521 0.56750769 0.93114904]]


### Task 3: Create a `5x5` matrix with row values ranging from `0` to `4`. Each row should be `[0, 1, 2, 3, 4]`.

In [4]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### Task 4: 
#### a. Generate a `(1000, 1000)`-shaped array and fill it with random samples drawn from a `standard normal distribution` (mean μ = 0 and standard deviation σ = 1).

In [5]:
arr_normal = np.random.randn(1000, 1000)
print(arr_normal)


[[ 1.38381406  0.64605556  0.58437124 ...  0.23732887  0.3713211
  -0.43787878]
 [-1.28184427  1.00110895  0.07733352 ... -0.98422262 -2.14259973
  -0.70062908]
 [-1.34899448  2.92117795 -0.89336414 ...  1.6962828  -0.29331224
   0.40388292]
 ...
 [-2.25453167 -0.11813457  1.31239674 ...  0.21587308 -0.90365132
  -0.52768504]
 [-2.02098564  0.10439576 -0.05060953 ...  0.07627127 -0.74738056
   1.04189053]
 [ 0.92533833  1.1087653   0.62378043 ... -0.23637127  0.8753115
  -1.03415348]]


#### b. Then, confirm that the `mean` and `standard deviation` closely approximate `0` and `1`, respectively.

In [6]:
mean_value = arr_normal.mean()
std_value = arr_normal.std()

print("Mean:", mean_value)
print("Standard Deviation:", std_value)


Mean: 0.00010024762973445315
Standard Deviation: 0.9996025473745017


### Task 5: Create a `7x7` NumPy array with random integers between `0` and `50`, inclusive. 

In [7]:
arr_random_ints = np.random.randint(0, 51, (7, 7))
print(arr_random_ints)

[[32 14 46  8 14 39 33]
 [44 21 50 15 32 15 13]
 [ 4 42 10 21 48 34 19]
 [11 22 38 16 19 26 28]
 [47 16 30 31 18  5 44]
 [40  5 11 44 45 37 20]
 [44 14  8 12 27  9 44]]


**a. Set all elements greater than `25` to their negative values.**

In [8]:
arr_random_ints[arr_random_ints > 25] *= -1
print(arr_random_ints)

[[-32  14 -46   8  14 -39 -33]
 [-44  21 -50  15 -32  15  13]
 [  4 -42  10  21 -48 -34  19]
 [ 11  22 -38  16  19 -26 -28]
 [-47  16 -30 -31  18   5 -44]
 [-40   5  11 -44 -45 -37  20]
 [-44  14   8  12 -27   9 -44]]


**b. Set all elements that are multiples of `5` to `0`.**

In [9]:
arr_random_ints[arr_random_ints % 5 == 0] = 0
print(arr_random_ints)

[[-32  14 -46   8  14 -39 -33]
 [-44  21   0   0 -32   0  13]
 [  4 -42   0  21 -48 -34  19]
 [ 11  22 -38  16  19 -26 -28]
 [-47  16   0 -31  18   0 -44]
 [  0   0  11 -44   0 -37   0]
 [-44  14   8  12 -27   9 -44]]


    **c. Compute the `sum`, `minimum`, and `maximum` of the array values following the transformations.**

In [10]:
arr_sum = arr_random_ints.sum()
arr_min = arr_random_ints.min()
arr_max = arr_random_ints.max()

print("Sum:", arr_sum)
print("Min:", arr_min)
print("Max:", arr_max)

Sum: -490
Min: -48
Max: 22


### Task 6: Create a `6x6` NumPy array with random integers between `10` and `99`, inclusive.

In [11]:
arr_6x6 = np.random.randint(10, 100, (6, 6))
print(arr_6x6)

[[54 30 54 53 81 35]
 [87 77 17 28 90 17]
 [13 84 23 35 44 99]
 [50 81 81 37 32 79]
 [96 86 88 96 96 29]
 [12 30 73 80 75 63]]


**a. Calculate the `sum` of each `row`.**

In [12]:
row_sums = arr_6x6.sum(axis=1)
print(row_sums)

[307 316 298 360 491 333]


**b. Calculate the `sum` of each `column`.**

In [13]:
col_sums = arr_6x6.sum(axis=0)
print(col_sums)

[312 388 336 329 418 322]


**c. Normalize each `row` so that its values `sum to 1`.**

In [14]:
row_sums = arr_6x6.sum(axis=1, keepdims=True)
normalized_rows = arr_6x6 / row_sums
print(normalized_rows)

[[0.17589577 0.09771987 0.17589577 0.17263844 0.26384365 0.11400651]
 [0.27531646 0.24367089 0.05379747 0.08860759 0.28481013 0.05379747]
 [0.04362416 0.28187919 0.07718121 0.11744966 0.14765101 0.33221477]
 [0.13888889 0.225      0.225      0.10277778 0.08888889 0.21944444]
 [0.19551935 0.17515275 0.17922607 0.19551935 0.19551935 0.05906314]
 [0.03603604 0.09009009 0.21921922 0.24024024 0.22522523 0.18918919]]


### Task 7: Create a random array of size `20` and replace the `maximum` value by `0` and the `minimum` value by `-1`.

In [15]:
arr_20 = np.random.rand(20)
arr_20[arr_20.argmax()] = 0
arr_20[arr_20.argmin()] = -1
print(arr_20)


[ 0.16340005  0.07216423  0.4927121   0.83423401  0.43031581  0.17372183
  0.88774567  0.62817578 -1.          0.62206874  0.36868069  0.15814291
  0.56217808  0.38919874  0.78993652  0.53301034  0.31965003  0.51104155
  0.14206446  0.43500996]


### Task 8: Generate the first `20` numbers of the Fibonacci sequence and store them in a NumPy array. Use a loop or vectorized operations to compute the sequence.

In [16]:
fib = np.zeros(20, dtype=int)
fib[0], fib[1] = 0, 1
for i in range(2, 20):
    fib[i] = fib[i-1] + fib[i-2]
print(fib)

[   0    1    1    2    3    5    8   13   21   34   55   89  144  233
  377  610  987 1597 2584 4181]


### Task 9: What is the equivalent of `enumerate` for numpy arrays? Illustrate the syntax by iterating through a 2D array that you create.

In [17]:
arr_2d = np.array([[10, 20, 30], [40, 50, 60]])

for index, value in np.ndenumerate(arr_2d):
    print(f"Index: {index}, Value: {value}")
#equivalent of enumerate is np.ndenumerate

Index: (0, 0), Value: 10
Index: (0, 1), Value: 20
Index: (0, 2), Value: 30
Index: (1, 0), Value: 40
Index: (1, 1), Value: 50
Index: (1, 2), Value: 60


### Task 10: How do you find the common values between two arrays?

In [ ]:
#np.intersect1d